// import Notiflix from 'notiflix';
// Notiflix.Notify.init({
//   width: '500px',
//   margin: 0,
//   padding: 0,
//   position: 'center-top',
//   distance: '140px',
//   opacity: 1,
//   borderRadius: '2px',
//   rtl: false,
//   timeout: 3000000,
//   messageMaxLength: 110,
//   backOverlay: false,
//   backOverlayColor: 'rgba(0,0,0,0.5)',
//   plainText: true,
//   showOnlyTheLastOne: false,
//   clickToClose: false,
//   pauseOnHover: true,
//   ID: 'NotiflixNotify',
//   className: 'notiflix-notify',
//   zindex: 4001,
//   fontFamily: 'Georgia',
//   fontSize: '14px',
//   cssAnimation: true,
//   cssAnimationDuration: 400,
//   cssAnimationStyle: 'from-right',
//   closeButton: false,
//   useIcon: true,
//   useFontAwesome: false,
//   fontAwesomeIconStyle: 'basic',
//   fontAwesomeIconSize: '34px',
//   failure: {
//     background: 'transparent',
//     textColor: '#FF001B',
//     childClassName: 'notiflix-notify-failure',
//     notiflixIconColor: 'none',
//     fontAwesomeClassName: 'fas fa-times-circle',
//     fontAwesomeIconColor: 'rgba(0,0,0,0.2)',
//     backOverlayColor: 'rgba(255,85,73,0.2)',
//   },
//   warning: {
//     background: 'transparent',
//     textColor: '#FF001B',
//     childClassName: 'notiflix-notify-warning',
//     notiflixIconColor: 'transparent',
//     fontAwesomeClassName: 'fas fa-exclamation-circle',
//     fontAwesomeIconColor: 'rgba(0,0,0,1)',
//     backOverlayColor: 'rgba(238,191,49,0.2)',
//   },
// });